name: RouterNet
main: de.mickare.routernet.mc.bukkit.NetPlugin
version: 0.0.2
website: https://github.com/mickare/RouterNet-Minecraft
authors: [mickare]
description: RouterNet Client for Bukkit
commands:
