name: RouterNet
main: de.rennschnitzel.routernet.mc.bungee.NetPlugin
version: 0.0.2
website: https://github.com/mickare/RouterNet-Minecraft
authors: [mickare]
description: RouterNet Client for BungeeCord